### ISSUE TITLE
Request - Flow Annotations Off by default

### ISSUE THREAD

**Issue by louiesolomon** [sonburn/sncr-sketch-plugin#3]
Firstly, thank you for the extremely useful plugin.

I'd like to put in a request to make the automatically generated artboard annotations when creating flows off by default. This option is found in Plugins > SNCR > Layer Annotations > Settings.

**Comment by sonburn** [comment]
@louiesolomon thanks for the feedback. I just pushed an enhancement and I included your suggestion as well.

I am surprised someone outside my company is using this plugin (because it's complex and poorly documented), but happy to hear it's providing value for you!
